### ISSUE TITLE
Fails with "UnknownTaskException: Task with name 'jar' not found in root project"

### ISSUE THREAD

**Issue by Flowdalic** [aalmiray/clirr-gradle-plugin#2]
I tried to add support for clirr-gradle-plugin to Smack's build system. It works for subprojects, but as soon as I move the

    apply plugin: 'org.kordamp.gradle.clirr'

statement out of the `subprojects` block, Smack throws the above error message. Of course I want to apply the clirr plugin also on the root project, so that I can define a task like

```groovy
task clirrRootReport(type: org.kordamp.gradle.clirr.ClirrReportTask) {
     dependsOn = subprojects.tasks.clirr
     reports = files(subprojects.tasks.clirr.xmlReport)
}
```

The current state of my clirr experiments are https://github.com/Flowdalic/Smack/commit/a8e43f8db17e4cad1d5abcab76a1f0c539848bc9.
The full error log can be found at http://dpaste.com/3YDZ2E6

I've also try to comment out the `jar` block in Smack's build.gradle, so that the root project has an jar artifact. Still the result is the same. Help greatly appreciated.

**Comment by aalmiray** [comment]
The clirr plugin does not yet handle aggregated reports. However you can generate them as long as you do not apply the `clirr` plugin to the root. this is how the Griffon project does it

  https://github.com/griffon/griffon/blob/development/build.gradle

Notice that only subprojects have the `clirr` plugin applied.
Aggregated reports will come in a future release.

**Comment by Flowdalic** [comment]
Thanks for pointing this out.

As it turns out, the problem was specifying the clirrRootReport task before the `subprojects` block where the clirr property was defined.

It does work now. Thanks again for your help. :)
