### ISSUE TITLE
Add heuristic to determine the baseline version automatically

### ISSUE THREAD

**Issue by Flowdalic** [aalmiray/clirr-gradle-plugin#3]
It would be great if the plugin would automatically determine the baseline version automatically, so that I don't have to change it manually between releases.

My project only guarantees API compatibility between patchlevel releases (1.2.1, 1.2.3. 1.2.42, ...), so a simply heuristic could look like

1. Remove the snapshot qualifier, i.e. `-SNAPSHOT-X`
2. Remove all release qualifiers, i.e. `-alphaX`, `-betaX`, `-rcX`, where `X` is an arbitrary number of digits
3. If the patchlevel number is 
  - `0`, then don't run clirr because there is no previous release to test against
  - otherwise decrement the patchlevel by one and run clirr against that release

**Comment by aalmiray** [comment]
Hmm removing `-SNAPSHOT`may be tricky. as some projects jump from `1.0.0` to `1.1.0` between snapshots, that is, no patch level. Automatically removing `-SNAPSHOT` would attempt to compare `1.1.0-SNAPSHOT` against `1.1.0` and that's wrong.

I wonder if a custom version resolution mechanism could be enabled, so that you may inject your own logic as long as `baseline` is not specified (but I believe is annotated with @Input). Hmm, choices, choices.

**Comment by Flowdalic** [comment]
> Automatically removing -SNAPSHOT would attempt to compare 1.1.0-SNAPSHOT against 1.1.0 and that's wrong.

Nope, because if the patchlevel version is `0`, clirr should not run at all (see step 3.)

**Comment by aalmiray** [comment]
Correct. According to your particular project rules the patch level `0` would prevent clirr for running. However the rule would break on projects that do not follow the patch level rule, which is the case of Griffon. So far we haven't had the need to use the patch level as every release brings new features, so we bump the minor number and leave patch as `0`.

Current version is set to `2.3.0-SNAPSHOT`.  Automatically removing the tag will attempt to compare it against `2.3.0` but it should be `2.2.0`.

I'm not saying the idea is without merit, what I'm saying that some rules look to be more specific to the workflow of the projects that you work with. This workflow may not apply to other projects. I think we can come to a compromise and make everyone happy, wouldn't you agree?

**Comment by Flowdalic** [comment]
I think is pretty "easy" to serve both use cases:

Common steps
---------------------

1. Remove the snapshot qualifier, i.e. `-SNAPSHOT-X`
2. Remove all release qualifiers, i.e. `-alphaX`, `-betaX`, `-rcX`, where `X` is an arbitrary number of digits

Non-Semver (only API compatiblity between patchlevel releases):
------------------


3. If the patchlevel number is 
  - `0`, then don't run clirr because there is no previous release to test against
  - otherwise decrement the patchlevel by one and run clirr against that release

Semver
----------

3. If the minor version is
  - `0`, then check patchlevel version, if it is
    - `0`, then don't run clirr
    - otherwise decrement patchlevel and run clirr with that as baseline
  - then check patchlevel, if it is
    - `0` then, decrement minor by one and run clirr with that as baseline
    - otherwise decrement minor by one and run clirr with that as baseline

**Comment by aalmiray** [comment]
2.0.0 => no run
    2.0.4 => 2.0.3
    2.1.0 => 2.0.0 (*)
    2.1.3 => 2.1.2

(*) I suppose if one would like to check 2.1.0-SNAPSHOT against 2.0.9 then the baseline has to be made explicit, right?

**Comment by Flowdalic** [comment]
Non-Semver
---------------

2.0.0 => no run
2.0.4 => 2.0.3
2.1.0 => no run (API binary compatibility is not guranteed between any version prior 2.1.0)
2.1.3 => 2.1.2

Semver
----------

2.0.0 => no run
2.0.4 => 2.0.3
2.1.0 => 2.0.0
2.1.3 => 2.1.2 **

** this made me realize that there is a bug in the description of the semver case. It must read
"decrement **patchlevel** by one" if `minor != 0 && patchlevel != null`. Now fixed.

> (*) I suppose if one would like to check 2.1.0-SNAPSHOT against 2.0.9 then the baseline has to be made explicit, right?

Yes, If you use non-semver, then releases with a 0 patchlevel likely don't have a binary compatible prior version (or in other words, it's not guranteed that they have one).

**Comment by Flowdalic** [comment]
:+1: Please remember me to buy you an beverage of your choice if we ever meet. :)

:tada:
