### ISSUE TITLE
Adding new subproject causes build failure when clirr-plugin is enabled

### ISSUE THREAD

**Issue by Flowdalic** [aalmiray/clirr-gradle-plugin#4]
If I add a new subproject to my gradle build which applies the clirr-plugin to all subprojects, then gradle will fail with "Could not resolve all dependencies", because it tries to resolve the baseline decency of the newly added subproject.

Of course I could configure gradle so that it won't apply the clirr plugin to the new subproject, but it feels like the better approach would be adding a new `enabled` property to the clirr plugin configuration. This would allow me to

````groovy
clirr {
    enabled = false
}
````

in the `subproject/build.gradle`

**Comment by aalmiray** [comment]
:+1: I like the idea of an `enabled` property.
