### ISSUE TITLE
Fails with "Error executing 'clirr' task. uber.org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18"

### ISSUE THREAD

**Issue by Flowdalic** [aalmiray/clirr-gradle-plugin#6]
I didn't dive into this yet. Quick Google search doesn't seem to return good pointers. Running gradle with `--stacktrace` yields no stacktrace.

```bash
:smack-core:clirr
Error executing 'clirr' task. uber.org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18 
```

**Comment by aalmiray** [comment]
I believe the problem is BCEL 5.2 which is unable to correctly parse Java8. BCEL 6.0 will fix this but is in an unreleased state; we don't want to rely on public snapshots or private builds.

**Comment by Flowdalic** [comment]
I use `target=1.7`, so there should be no java 8 bytecodes in the classes.

**Comment by aalmiray** [comment]
Are you using JDK8 to compile? More info about the error can be found at https://issues.apache.org/jira/browse/BCEL-173

**Comment by Flowdalic** [comment]
Indeed I use javac from JDK8 to compile.

Fun fact: Just yesterday I removed JKD7 from my desktop, because JDK8 seems to be mature enough. I still think it's mature, just some advanced auxiliary tools seem to have problems

**Comment by zxxz** [comment]
@aalmiray I know that there is no ETA for the release of BCEL 6.0, but, on May 5th Dave Brosius suggested in this [post on apache](https://issues.apache.org/jira/browse/BCEL-173?focusedCommentId=14528370&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14528370) to use the [com.google.code.findbugs:bcel-findbugs:6.0](http://search.maven.org/#artifactdetails|com.google.code.findbugs|bcel-findbugs|6.0|jar) while waiting for the release 6.0.
Perhaps this is better than a public snapshot or a private build? If so, where this dependency should be declared (I am new to gradle... :-().

**Comment by aalmiray** [comment]
The BCEL library is included inside the clirr JAR (using the shadow plugin, classes are relocated). A new release of the clirr-gradle plugin must be made to accommodate this binary change.

**Comment by Flowdalic** [comment]
For what it's worth: I see no reason to switch to bcel-findbugs. The error seems to be non fatal and clirr still works just fine. It's just a cosmetic issue. At least for me.

**Comment by aalmiray** [comment]
Inability to properly deal with JDK8 leads to incomplete reports. this is the reason why the `ignoreFailures` flag was added. I'd rather stay with Apache BCEL but the project seems to have reached an impasse regarding the 6.0 release. sigh

**Comment by Flowdalic** [comment]
Ahh right, I remember. How about using a stable/fixed snapshot dependency to BCEL 6.0 then? Gradle supports this lately.

**Comment by aalmiray** [comment]
Like @zxxz suggested, looks like `com.google.code.findbugs:bcel-findbugs:6.0` does the trick. I no longer get the error mentioned at the top of this issue. I'm thinking in giving Apache BCEL two more weeks to get their act together; otherwise the next release of clirr-gradle-plugin will switch to bcle-findbugs.

**Comment by aalmiray** [comment]
Released version 2.3.0 with `bcel-findbugs` as an internal dependency.

**Comment by Flowdalic** [comment]
Thanks. Could it be that you forgot to push the code?

**Comment by aalmiray** [comment]
Ack! Was so excited about the release I forgot the commit :cry: 
It's fixed now.
